name: Publish release to NPM

on:
    push:
        tags:
            - "v*"

jobs:
    npm-publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Create release from tag
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Publish to NPM
              uses: JS-DevTools/npm-publish@v1
              with:
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}
