name: Tag & Release New Versions

on:
    push:
        branches: [master, main]

jobs:
    tag:
        name: tag
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Installing
              run: yarn

            - name: Testing Build
              run: yarn build

            - name: Linting
              run: yarn lint

            - name: Unit Testing
              run: yarn test

            - uses: salsify/action-detect-and-tag-new-version@v2
              with:
                  version-command: |
                      cat ./package.json | jq --raw-output '.version'
